openapi: 3.1.1
info:
  title: Tilgangsstyring av arbeidsgivere med Altinn
  description: |
    Dette api-et lar appen din se hvilke tilganger en innlogget bruker har i
    hvilke virksomheter/bedrifter.

    Med innlogget bruker, mener vi at api-et vårt kun godtar kall med
    on-behalf-of access token for brukeren.

    Dersom dere har en applikasjon hvor bruker ikke er en del av flyten, og dere derfor ikke har en obo-token, kan dere benytte m2m-token. 

    ## Hvordan du kaller dev-gcp-api-et fra denne siden

    For at du skal kunne kalle dev-gcp-api-et vårt direkte her fra swagger, må
    du lage en [developer
    token](https://doc.nais.io/auth/entra-id/how-to/generate/): 

    1. Åpne i nettleseren:
        - for obo-token: [https://tokenx-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:fager:arbeidsgiver-altinn-tilganger&acr=idporten-loa-high](https://tokenx-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:fager:arbeidsgiver-altinn-tilganger&acr=idporten-loa-high).
        - for m2m-token: [https://azure-token-generator.intern.dev.nav.no/api/m2m?aud=dev-gcp:fager:arbeidsgiver-altinn-tilganger](https://azure-token-generator.intern.dev.nav.no/api/m2m?aud=dev-gcp:fager:arbeidsgiver-altinn-tilganger).
    2. Logg inn med *test*-brukeren du ønsker token for. 
    3. Kopier ut tokenet fra `"access_token"`-feltet. Ikke ta med fnuttene (`"`).
    4. Klikk på *Authorize*-knappen nede til høyre, lim inn tokenet, og trykk på *Authorize* og *Close*.


    Om du foretrekker curl, postman eller noe annet, må du legge ved tokenet som
    en header i HTTP-requesten:

    ```

    Authorization: Bearer tokenet-fra-steg-3-her

    ```

    ## Hvordan ta i bruk APIet

    For at dere skal kunne bruke dette APIet må et par ting på plass. Access policy må settes opp hos dere og oss.    
    I tillegg så må vi vite hvilken altinn 3 ressurs dere skal benytte.
    Grunnen til dette er en begrensning i altinn 3 authorizedResources apiet som brukes. Her returneres kun eksplisitt delegerte tilganger.
    Det vil si at tilganger som delegeres via roller må slås opp i tillegg. Dette gjør APIet vårt for dere dersom dere sier ifra til oss.
    På sikt skal altinn komme med et nytt api som vil returnere alle tilganger, også de implisitt delegerte via roller og tilgangspakker. 
    I mellomtiden må dere si ifra til oss om hvilke altinn 3 ressurser dere skal bruke. 
    Dersom dere ikke gjør dette vil kun eksplisitt delegerte tilganger bli returnert. Dvs de som har gitt eller fått en ressurs delegert på person nivå.

    ## Access policy i dev-gcp og prod-gcp

    Du må legge på [outbound access
    policy](https://doc.nais.io/workloads/how-to/access-policies/#send-requests-to-other-app-in-another-namespace)

    i appen din, slik som dette (bytt ut `prod-gcp` med `dev-gcp` i test):

    ```

    accessPolicy:
      outbound:
        rules:
          - application: arbeidsgiver-altinn-tilganger
            namespace: fager
            cluster: prod-gcp
    ```


    Du må også be oss om å legge til appen deres i vår inbound access policy.
    
    Du kontakter oss i [slack kanalen #team-fager](https://nav-it.slack.com/archives/C01V9FFEHEK).
    
    ## Litt om migrering fra altinn 2 til altinn 3
    
    I Altinn 2 styres tilganger av servicecode og serviceedition. I altinn 3 er det ressurser som styrer tilganger.
    Dersom dere allerede har en altinn 2 tilgang og skal migrere denne, så kan dette apiet også lette overgangen.

    Internt i applikasjonen er det en oversikt over hvilke altinn 3 ressurser som erstatter hvilke altinn 2 tilganger.
    For disse ressursene vil vi returnere altinn 2 tilgangen i tillegg til altinn 3 ressursen. 
    På denne måten står man litt mer frikoblet fra "turn-key" migreringen i altinn. 
    Med andre ord vil de som hadde tilgang til for eksempel notifikasjoner for en altinn 2 tjeneste ikke miste disse på grunn av migrering av tjenesten fra altinn 2 servicecode til altinn 3 ressurs.

    Dersom det ikke er ønskelig at vi returnerer altinn 2 tilganger i tillegg til altinn 3 ressursene, så kan vi enkelt gjøre unntak for enkelte tjenester. Bare gi oss beskjed. 
  
    Dette er litt vanskelig å kommunisere skriftlig, så vi tar gjerne en prat om dette dersom det er behov.

    ## Ingresser

    Produksjon:

    - prod-gcp (service discovery):
    `http://arbeidsgiver-altinn-tilganger.fager/`

    - prod-fss: ikke satt opp, ta kontakt ved behov


    Testmiljø, som bruker Altinns tt02-miljø:

    - dev-gcp (service discovery, anbefalt):
    `http://arbeidsgiver-altinn-tilganger.fager/`

    - dev-gcp (ingress):
    `https://arbeidsgiver-altinn-tilganger.intern.dev.nav.no`

    - dev-fss: ikke satt opp, ta kontakt ved behov


    Bruk ingress-versjonen for å lese dokumentasjon og

    når du eksperimenterer med curl, post-man eller

    lignende.  Bruk service discovery fra appen din.


    ## Autentisering av kall mot api-et

    Du må legge ved en header på følgende form når du kaller api-et vårt:

    ```

    Authorization: Bearer et-token-fra-tokenx-her

    ```

    Først må du sette opp access policy [som beskrevet over](#).

    Når du skal gjøre et http-kall, må appen din 

    skaffe seg et token som [beskrevet i
    nais-dokumentasjonen](https://doc.nais.io/auth/tokenx/how-to/consume/).


    ## Retry av driftsforstyrrelser


    Vi anbefaler at dere har retry i klienten deres ved driftsforstyrrelser. 

    Feks HTTP 502, 503, 504 kan forsøkes på nytt et par ganger før dere gir opp
    og gir feilmelding til brukeren.
  version: local
externalDocs:
  url: /
servers:
  - url: https://arbeidsgiver-altinn-tilganger.intern.dev.nav.no
    description: dev-gcp
  - url: http://0.0.0.0:8080
    description: Local mock server
tags: [ ]
paths:
  /m2m/whoami:
    get:
      tags: [ ]
      description: Hvem er jeg autentisert som?
      parameters: [ ]
      responses:
        '401':
          description: >-
            Når vi ikke aksepterer tokenet du sendte i Authorization-headeren.
            Vi sjekker blant annet at tokenet:

            - ikke er utgått

            - har `acr`-claim med `Level4` eller `idporten-loa-high`

            - har riktig audience og issuer (`aud` og `iss`)
          headers: { }
      deprecated: false
      security:
        - BearerAuth: [ ]
  /m2m/altinn-tilganger:
    post:
      tags: [ ]
      description: >-
        Hent tilganger fra Altinn for en bruker på fnr autentisert som entra
        m2m.
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/no.nav.fager.AltinnTilgangerM2MRequest'
            examples:
              no_filter:
                summary: Ingen filter
                value:
                  fnr: "11123456789"
              filter_inkluder_slettede:
                summary: Returnerer også slettede enheter. Tilganger knyttet til slettede enheter vil inkluderes dersom de finnes.
                value:
                  filter:
                    inkluderSlettede: true
              filter_altinn2:
                summary: filtrer på en eller flere altinn 2 tjenester
                value:
                  fnr: "11123456789"
                  filter:
                    altinn2Tilganger: [ "4936:1" ]
              filter_altinn3:
                summary: filtrer på en eller flere altinn 3 ressurser
                value:
                  fnr: "11123456789"
                  filter:
                    altinn3Tilganger: [ "nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger" ]
              filter_altinn2eller3:
                summary: filtrer på en eller flere altinn 2 tjenester og en eller flere altinn 3 ressurser
                value:
                  fnr: "11123456789"
                  filter:
                    altinn2Tilganger: [ "4936:1" ]
                    altinn3Tilganger: [ "nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger" ]
      responses:
        '200':
          description: Successful Request
          headers: { }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/no.nav.fager.AltinnTilgangerResponse'
              examples:
                Successful Respons:
                  $ref: '#/components/examples/tilganger_success'
        '401':
          description: >-
            Når vi ikke aksepterer tokenet du sendte i Authorization-headeren.
            Vi sjekker blant annet at tokenet:

            - ikke er utgått

            - har `acr`-claim med `Level4` eller `idporten-loa-high`

            - har riktig audience og issuer (`aud` og `iss`)
          headers: { }
      deprecated: false
      security:
        - BearerAuth: [ ]
  /whoami:
    get:
      tags: [ ]
      description: Hvem er jeg autentisert som?
      parameters: [ ]
      responses:
        '401':
          description: >-
            Når vi ikke aksepterer tokenet du sendte i Authorization-headeren.
            Vi sjekker blant annet at tokenet:

            - ikke er utgått

            - har `acr`-claim med `Level4` eller `idporten-loa-high`

            - har riktig audience og issuer (`aud` og `iss`)
          headers: { }
      deprecated: false
      security:
        - BearerAuth: [ ]
  /altinn-tilganger:
    post:
      tags: [ ]
      description: Hent tilganger fra Altinn for innlogget bruker.
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/no.nav.fager.AltinnTilgangerRequest'
            required: false
            examples:
              no_filter:
                summary: Ingen filter (trenger ikke noe i body)
                value: "{}"
              filter_inkluder_slettede:
                summary: Returnerer også slettede enheter. Tilganger knyttet til slettede enheter vil inkluderes dersom de finnes.
                value:
                  filter:
                    inkluderSlettede: true
              filter_altinn2:
                summary: filtrer på en eller flere altinn 2 tjenester
                value:
                  filter:
                    altinn2Tilganger: [ "4936:1" ]
              filter_altinn3:
                summary: filtrer på en eller flere altinn 3 ressurser
                value:
                  filter:
                    altinn3Tilganger: [ "nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger" ]
              filter_altinn2eller3:
                summary: filtrer på en eller flere altinn 2 tjenester og en eller flere altinn 3 ressurser
                value:
                  filter:
                    altinn2Tilganger: [ "4936:1" ]
                    altinn3Tilganger: [ "nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger" ]
        required: false
      responses:
        '200':
          description: Successful Request
          headers: { }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/no.nav.fager.AltinnTilgangerResponse'
              examples:
                Successful Respons:
                  $ref: '#/components/examples/tilganger_success'
        '401':
          description: >-
            Når vi ikke aksepterer tokenet du sendte i Authorization-headeren.
            Vi sjekker blant annet at tokenet:

            - ikke er utgått

            - har `acr`-claim med `Level4` eller `idporten-loa-high`

            - har riktig audience og issuer (`aud` og `iss`)
          headers: { }
      deprecated: false
      security:
        - BearerAuth: [ ]
components:
  schemas:
    no.nav.fager.Filter:
      title: Filter
      type: object
      properties:
        altinn2Tilganger:
          title: Set<String>
          uniqueItems: true
          type: array
          items:
            title: String
            type: string
        altinn3Tilganger:
          title: Set<String>
          uniqueItems: true
          type: array
          items:
            title: String
            type: string
        inkluderSlettede:
          title: Inkluder slettede
          type: boolean
          description: |
            Dersom satt til true, vil også slettede enheter inkluderes i resultatet.
            Standardverdien er false, og slettede enheter utelates da fra responsen.
            Eventuelle tilganger knyttet til en slettet enhet vil også returneres dersom de finnes.
          default: false
      description: >-

        Filter for hvilke tilganger som skal hentes. Dersom flere filter er
        angitt tolkes dette som logisk OR.

        Trenger dere en annen logikk kan dere kontakte teamet så kan vi
        prioritere å støtte det. 


        Filterne har et hardkodet sett med gyldige verdier. 

        Dersom dere angir en verdi utenfor det gyldige settet vil det returneres
        en HTTP 400 feil som angir den ugyldige verdien, samt hva som er
        tillatt.

        Gyldige verdier varierer i dev og prod for noen servicecode/version
        kombinasjoner. Derfor er de ikke dokumentert her.

        De gyldige verdiene finner dere i kildekoden:
        https://github.com/navikt/arbeidsgiver-altinn-tilganger/blob/main/src/main/kotlin/no/nav/fager/altinn/ResourceRegistry.kt#L18. 

        KnownAltinn2Tjenester (altinn2) og KnownResourceIds (altinn3)  


        Dersom dere trenger andre verdier kan dere kontakte teamet så legger vi
        dem til.


        Til slutt en liten caveat: Filtrering gjøres på løvnoder/virksomheter.
        Her antas det at overordnede enhet ikke har tilganger som ikke er
        delegert til en av sine underenheter.

        Logikken er nå slik at dersom en parent har tjenesten, men ingen av
        underenhetene har den så vil parenten også fjernes.

        Dette er for å hindre at en overordnet enhet blir til laveste nivå.

        Dette er en antakelse vi har gjort basert på observasjoner i dev. 

        Dersom det viser seg at tjenester delegeres ekspisitt på overordnet nivå
        og det er noe dere trenger at vi støtter ta kontakt med oss. 

    no.nav.fager.AltinnTilgangerM2MRequest:
      title: AltinnTilgangerM2MRequest
      required:
        - fnr
      type: object
      properties:
        filter:
          $ref: '#/components/schemas/no.nav.fager.Filter'
        fnr:
          title: String
          type: string
    no.nav.fager.AltinnTilgang:
      title: AltinnTilgang
      required:
        - altinn2Tilganger
        - altinn3Tilganger
        - navn
        - organisasjonsform
        - orgnr
        - erSlettet
        - underenheter
      type: object
      properties:
        altinn2Tilganger:
          title: Set<String>
          uniqueItems: true
          type: array
          description: Tilganger til Altinn 2
          items:
            title: String
            type: string
        altinn3Tilganger:
          title: Set<String>
          uniqueItems: true
          type: array
          description: Tilganger til Altinn 3
          items:
            title: String
            type: string
        erSlettet:
          title: Enhet er slettet
          type: boolean
          description: |
            Enhet er slettet
          default: false
        navn:
          title: String
          type: string
          description: Navn på organisasjonen
        organisasjonsform:
          title: String
          type: string
          description: >-
            Organisasjonsform. se
            https://www.brreg.no/bedrift/organisasjonsformer/
          example: BEDR
        orgnr:
          title: String
          type: string
          description: Organisasjonsnummer
          example: '11223344'
        underenheter:
          title: List<AltinnTilgang>
          type: array
          description: >-
            list av underenheter til denne organisasjonen hvor brukeren har
            tilganger
          items:
            $ref: '#/components/schemas/no.nav.fager.AltinnTilgang'
      description: Brukerens tilganger til Altinn 2 og Altinn 3 for en organisasjon
    no.nav.fager.AltinnTilgangerResponse:
      title: AltinnTilgangerResponse
      required:
        - hierarki
        - isError
        - orgNrTilTilganger
        - tilgangTilOrgNr
      type: object
      properties:
        hierarki:
          title: List<AltinnTilgang>
          type: array
          description: Organisasjonshierarkiet med brukerens tilganger
          items:
            $ref: '#/components/schemas/no.nav.fager.AltinnTilgang'
        isError:
          title: Boolean
          type: boolean
          description: >-
            Om det var en feil ved henting av tilganger. Dersom denne er true
            kan det bety at ikke alle tilganger er hentet.
        orgNrTilTilganger:
          title: Map<String,Set<String>>
          type: object
          additionalProperties:
            title: Set<String>
            uniqueItems: true
            type: array
            items:
              title: String
              type: string
          description: >-
            Map fra organisasjonsnummer til tilganger. Convenience for å slå opp
            tilganger på orgnummer.
        tilgangTilOrgNr:
          title: Map<String,Set<String>>
          type: object
          additionalProperties:
            title: Set<String>
            uniqueItems: true
            type: array
            items:
              title: String
              type: string
          description: >-
            Map fra tilgang til organisasjonsnummer. Convenience for å slå opp
            orgnummer på tilgang.
    no.nav.fager.AltinnTilgangerRequest:
      title: AltinnTilgangerRequest
      type: object
      properties:
        filter:
          $ref: '#/components/schemas/no.nav.fager.Filter'
  examples:
    tilganger_success:
      value:
        hierarki:
          - orgnr: '987654321'
            erSlettet: false
            altinn3Tilganger: [ ]
            altinn2Tilganger: [ ]
            underenheter:
              - orgnr: '123456789'
                erSlettet: false
                altinn3Tilganger:
                  - tilgang1
                  - tilgang2
                altinn2Tilganger:
                  - serviceCode:serviceEdition
                underenheter: [ ]
                navn: Organisasjon 2
                organisasjonsform: BEDR
            navn: Organissjon 1
            organisasjonsform: ORGL
        orgNrTilTilganger:
          '123456789':
            - serviceCode:serviceEdition
            - tilgang1
            - tilgang2
        tilgangTilOrgNr:
          serviceCode:serviceEdition:
            - '123456789'
          tilgang1:
            - '123456789'
          tilgang2:
            - '123456789'
        error: false
  securitySchemes:
    BearerAuth:
      type: http
      description: >-
        Du skaffer deg et token som du kan bruke her ved å logge inn med
        test-bruker på [denne nettsiden](

        https://tokenx-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:fager:arbeidsgiver-altinn-tilganger&acr=idporten-loa-high

        ) og bruker veriden fra `"access_token"`-feltet. Ikke ta med fnuttene
        (`"`).
      scheme: bearer
      bearerFormat: JWT
